name: CI/CD
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch CI/CD Tool
        run: |
          curl -L -o cicd.zip https://github.com/VinnieApps/cicd-toolbox/releases/latest/download/cicd_linux_amd64.zip \
            && unzip -d cicd-dir cicd.zip \
            && cp cicd-dir/cicd cicd

      - name: Calculate Next Version
        run: |
          ./cicd semantic-release version-file vinnieapps/mechanic
          cat .version

      - name: Test
        run: ./cicd golang run-tests

      - name: Show Coverage
        run: go tool cover -func=build/coverage/all.out

      - name: Build mechanic
        run: |
          version=$(cat .version)
          ./cicd golang build --base-name mechanic \
            --os windows --os darwin --os linux \
            --ldflags "-X main.version=$version" \
            --arch amd64 \
            cmd/mechanic/main.go

      - name: Copy binaries
        if: github.ref == 'refs/heads/master'
        run: |
          mkdir -p build/packages
          cp build/binaries/darwin_amd64/mechanic build/packages/mechanic_darwin_amd64
          cp build/binaries/linux_amd64/mechanic build/packages/mechanic_linux_amd64
          cp build/binaries/windows_amd64/mechanic.exe build/packages/mechanic_windows_amd64.exe

      - name: Release
        if: github.ref == 'refs/heads/master'
        run: ./cicd semantic-release publish-release vinnieapps/mechanic --github-token ${{ secrets.GITHUB_TOKEN }} --upload build/packages
